### ISSUE TITLE
make install DESTDIR=... fails on symbolic link creation (unprivileged install)

### ISSUE THREAD

**Issue by cfelder** [scgmlz/BornAgain#124]
failed to create symbolic link 'thisbornagain.sh': Permission denied
failed to create symbolic link 'thisbornagain.csh': Permission denied
-- Up-to-date: /tmp/ba/usr/local/lib/BornAgain-1.7/bornagain/__init__.py
-- Up-to-date: /tmp/ba/usr/local/lib/BornAgain-1.7/bornagain/plot_utils.py
-- Up-to-date: /tmp/ba/usr/local/lib/BornAgain-1.7/_libBornAgainGUI.so
-- Up-to-date: /tmp/ba/usr/local/lib/BornAgain-1.7/exec/BornAgain
-- Up-to-date: /tmp/ba/usr/local/share/BornAgain-1.7/Images/BornAgain.ico
-- Up-to-date: /tmp/ba/usr/local/share/BornAgain-1.7/Images/BornAgain.icns
-- Up-to-date: /tmp/ba/usr/local/share/BornAgain-1.7/Images/BornAgain_48x48.png
-- Up-to-date: /tmp/ba/usr/local/share/BornAgain-1.7/Images/BornAgain_64x64.png
failed to create symbolic link 'bornagain': Permission denied

e.g. if configured with ``CMAKE_INSTALL_PREFIX=/usr/local``

``make install DESTDIR=/tmp/BornAgain``

should create those symlinks correctly in ``/tmp/BornAgain/usr/local/...``

**Comment by jwuttke** [comment]
Hopefully resolved in branch https://github.com/jwuttke/BornAgain/tree/gh124. The only modified file is Core/CMakeLists.txt.

**Comment by cfelder** [comment]
Still getting:

```
failed to create symbolic link 'thisbornagain.sh': Permission denied
failed to create symbolic link 'thisbornagain.csh': Permission denied
-- Installing: /tmp/ba/usr/local/lib/BornAgain-1.7/bornagain/__init__.py
-- Installing: /tmp/ba/usr/local/lib/BornAgain-1.7/bornagain/plot_utils.py
-- Installing: /tmp/ba/usr/local/lib/BornAgain-1.7/_libBornAgainGUI.so
-- Installing: /tmp/ba/usr/local/lib/BornAgain-1.7/exec/BornAgain
-- Installing: /tmp/ba/usr/local/share/BornAgain-1.7/Images/BornAgain.ico
-- Installing: /tmp/ba/usr/local/share/BornAgain-1.7/Images/BornAgain.icns
-- Installing: /tmp/ba/usr/local/share/BornAgain-1.7/Images/BornAgain_48x48.png
-- Installing: /tmp/ba/usr/local/share/BornAgain-1.7/Images/BornAgain_64x64.png
failed to create symbolic link 'bornagain': Permission denied
```

Furthermore it is necessary to ensure that ``DESTDIR`` is not used in compiled binaries. It should just copy the files to another destination (unprivileged installation)

**Comment by jwuttke** [comment]
Please retry with latest version of https://github.com/jwuttke/BornAgain/tree/gh124 (escaping the dollar in $$ENV{DESTDIR}).

**Comment by jwuttke** [comment]
reopen if still relevant
